progetto_settimanale/Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using progetto_settimanale.Models;


namespace progetto_settimanale.Controllers
{
    public class AnagraficaController : Controller
    {
        private readonly SqlConnection _connection;

        public AnagraficaController(SqlConnection connection)
        {
            _connection = connection;
        }

        public IActionResult Index()
        {
            var anagrafiche = new List<Anagrafica>();
            _connection.Open();
            string query = "SELECT * FROM ANAGRAFICA";
            using (SqlCommand cmd = new SqlCommand(query, _connection))
            {
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        anagrafiche.Add(new Anagrafica()
                        {
                            idanagrafica = reader.GetInt32(0),
                            Cognome = reader.GetString(1),
                            Nome = reader.GetString(2),
                            Indirizzo = reader.GetString(3),
                            Città = reader.GetString(4),
                            CAP = reader.GetString(5),
                            Cod_Fisc = reader.GetString(6),
                        });
                    }
                }
            }
            _connection.Close();
            return View(anagrafiche);
        }

        public IActionResult Aggiungi()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Aggiungi(Anagrafica anagrafica)
        {
            if (ModelState.IsValid)
            {
                _connection.Open();
                var query = "INSERT INTO ANAGRAFICA (Cognome, Nome, Indirizzo, Città, CAP, Cod_Fisc) VALUES (@Cognome, @Nome, @Indirizzo, @Città, @CAP, @Cod_Fisc)";
                using (var cmd = new SqlCommand(query, _connection))
                {
                    cmd.Parameters.AddWithValue("@Cognome", anagrafica.Cognome);
                    cmd.Parameters.AddWithValue("@Nome", anagrafica.Nome);
                    cmd.Parameters.AddWithValue("@Indirizzo", anagrafica.Indirizzo);
                    cmd.Parameters.AddWithValue("@Città", anagrafica.Città);
                    cmd.Parameters.AddWithValue("@CAP", anagrafica.CAP);
                    cmd.Parameters.AddWithValue("@Cod_Fisc", anagrafica.Cod_Fisc);
                    cmd.ExecuteNonQuery();
                }
                _connection.Close();

                return RedirectToAction("Index");
            }
            return View(anagrafica);
        }
    }
}

progetto_settimanale/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using progetto_settimanale.Models;
namespace progetto_settimanale.Controllers
{
    public class ReportController : Controller
    {
        private readonly SqlConnection _connection;

        public ReportController(SqlConnection connection)
        {
            _connection = connection;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TotaleVerbaliPerTrasgressore()
        {
            var listaTotale = new List<TotaleVerbaliPerTrasgressore>();
            try
            {
                _connection.Open();
                string query = @"
                   SELECT a.idanagrafica, a.Cognome, a.Nome, COUNT(v.idverbale) AS TotaleVerbali
                   FROM ANAGRAFICA a
                   JOIN VERBALE v ON a.idanagrafica = v.idanagrafica
                    GROUP BY a.idanagrafica, a.Cognome, a.Nome
                        ";
                using (SqlCommand cmd = new SqlCommand(query, _connection))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            listaTotale.Add(new TotaleVerbaliPerTrasgressore
                            {
                                idanagrafica = reader.GetInt32(0),
                                Cognome = reader.GetString(1),
                                Nome = reader.GetString(2),
                                TotaleVerbali = reader.GetInt32(3)
                            });
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                _connection.Close();
            }

            return View(listaTotale);
        }

        public IActionResult PuntiDecurtatiPerTrasgressore()
        {
            var listaTotale = new List<PuntiDecurtatiPerTrasgressore>();

            try
            {
                _connection.Open();
                string query = @"
                SELECT a.idanagrafica,a.Cognome, a.Nome, SUM(v.DecurtamentoPunti) as TotalePuntiDecurtati
                FROM Anagrafica a
                JOIN VERBALE v ON a.idanagrafica = v.idanagrafica
                GROUP BY a.idanagrafica, a.Cognome, a.Nome
                        ";
                using (SqlCommand cmd = new SqlCommand(query, _connection))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            listaTotale.Add(new PuntiDecurtatiPerTrasgressore
                            {
                                idanagrafica = reader.GetInt32(0),
                                Cognome = reader.GetString(1),
                                Nome = reader.GetString(2),
                                TotalePuntiDecurtati = reader.IsDBNull(3) ? 0 : reader.GetInt32(3),
                            });
                        }
                    }
                }

            } catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            } finally { _connection.Close(); }
            
            return View(listaTotale);
        }

        public IActionResult DecurtamentoPuntiSuperiore10Punti()
        {
            var listaTotale = new List<DecurtamentoPuntiSuperiore10Punti>();
            try
            {
                _connection.Open();
                string query = @"
                    SELECT a.idanagrafica, a.Cognome, a.Nome, v.DataViolazione, v.Importo, v.DecurtamentoPunti
                    FROM ANAGRAFICA a
                    JOIN VERBALE v ON a.idanagrafica = v.idanagrafica
                    WHERE v.DecurtamentoPunti > 10
                        ";
                
                using (SqlCommand cmd = new SqlCommand(query, _connection))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while(reader.Read())
                        {
                            listaTotale.Add(new DecurtamentoPuntiSuperiore10Punti
                            {
                                idanagrafica = reader.GetInt32(0),
                                Cognome = reader.GetString(1),
                                Nome = reader.GetString(2),
                                DataViolazione = reader.GetDateTime(3),
                                Importo = reader.GetDecimal(4),
                                DecurtamentoPunti = reader.GetInt32(5)
                            });
                        }
                    }
                }
            } catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            } finally
            {
                _connection.Close();
            }
            return View(listaTotale);
        }

        public IActionResult ViolazioniImportoMaggioreDi400()
        {
            var listaTotale = new List<ViolazioniImportoMaggioreDi400>();
            try
            {
                _connection.Open();
                string query = @"
                     SELECT v.idverbale, v.DataViolazione, v.Importo, v.DecurtamentoPunti, a.Cognome, a.Nome, tv.descrizione AS TipoViolazione
                     FROM VERBALE v
                     JOIN ANAGRAFICA a ON v.idanagrafica = a.idanagrafica
                     JOIN TIPO_VIOLAZIONE tv ON v.idviolazione = tv.idviolazione
                     WHERE v.Importo > 400
                    ";
                using (SqlCommand cmd = new SqlCommand(query, _connection))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            listaTotale.Add(new ViolazioniImportoMaggioreDi400
                            {
                                idverbale = reader.GetInt32(0),
                                DataViolazione = reader.GetDateTime(1),
                                Importo = reader.GetDecimal(2),
                                DecurtamentoPunti = reader.GetInt32(3),
                                Cognome = reader.GetString(4),
                                Nome = reader.GetString(5),
                                TipoViolazione = reader.GetString(6)
                            });
                        }
                    }
                }

            } catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                _connection.Close();
            }
            return View(listaTotale);
        }
    }
}

progetto_settimanale/Controllers/VerbaleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using progetto_settimanale.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace progetto_settimanale.Controllers
{
    public class VerbaleController : Controller
    {
        private readonly SqlConnection _connection;

        public VerbaleController(SqlConnection connection)
        {
            _connection = connection;
        }

        public IActionResult Index()
        {
            var verbali = new List<Verbale>();
            _connection.Open();
            string query = "SELECT * FROM VERBALE";
            using (SqlCommand cmd = new SqlCommand(query, _connection))
            {
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        verbali.Add(new Verbale()
                        {
                            idverbale = reader.GetInt32(0),
                            DataViolazione = reader.GetDateTime(1),
                            IndirizzoViolazione = reader.GetString(2),
                            Nominativo_Agente = reader.GetString(3),
                            DataTrascrizioneVerbale = reader.GetDateTime(4),
                            Importo = reader.GetDecimal(5),
                            DecurtamentoPunti = reader.GetInt32(6),
                            idanagrafica = reader.GetInt32(7),
                            idviolazione = reader.GetInt32(8),

                        });
                    }
                }
            }
            _connection.Close();
            return View(verbali);
        }

        public IActionResult Aggiungi()
        {
            var anagrafiche = new List<Anagrafica>();
            var violazione = new List<Violazione>();
            _connection.Open();

            using (var cmd = new SqlCommand("SELECT idanagrafica, Cognome, Nome FROM ANAGRAFICA", _connection))
            {
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        anagrafiche.Add(new Anagrafica
                        {
                            idanagrafica = reader.GetInt32(0),
                            Cognome = reader.GetString(1),
                            Nome = reader.GetString(2),
                        });
                    }
                }
            }


            using (var cmd = new SqlCommand("SELECT idviolazione, descrizione FROM TIPO_VIOLAZIONE", _connection))
            {
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        violazione.Add(new Violazione
                        {
                            idviolazione = reader.GetInt32(0),
                            descrizione = reader.GetString(1),
                        });
                    }
                }
            }

            _connection.Close();

            var anagraficheSelectList = anagrafiche.Select(a => new SelectListItem
            {
                Value = a.idanagrafica.ToString(),
                Text = $"ID {a.idanagrafica} - {a.Cognome} {a.Nome}"
            });

            ViewBag.Anagrafiche = new SelectList(anagraficheSelectList, "Value", "Text");
            ViewBag.Violazioni = new SelectList(violazione, "idviolazione", "descrizione");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Aggiungi(Verbale verbale)
        {
            if (ModelState.IsValid)
            {
                _connection.Open();
                var query = "INSERT INTO VERBALE (DataViolazione, IndirizzoViolazione, Nominativo_Agente, DataTrascrizioneVerbale, Importo, DecurtamentoPunti, idanagrafica, idviolazione) VALUES (@DataViolazione, @IndirizzoViolazione, @Nominativo_Agente, @DataTrascrizioneVerbale,@Importo, @DecurtamentoPunti, @idanagrafica, @idviolazione)";

                using (var cmd = new SqlCommand(query, _connection))
                {
                    cmd.Parameters.AddWithValue("@DataViolazione", verbale.DataViolazione);
                    cmd.Parameters.AddWithValue("@IndirizzoViolazione", verbale.IndirizzoViolazione);
                    cmd.Parameters.AddWithValue("@Nominativo_Agente", verbale.Nominativo_Agente);
                    cmd.Parameters.AddWithValue("@DataTrascrizioneVerbale", verbale.DataTrascrizioneVerbale);
                    cmd.Parameters.AddWithValue("@Importo", verbale.Importo);
                    cmd.Parameters.AddWithValue("@DecurtamentoPunti", verbale.DecurtamentoPunti);
                    cmd.Parameters.AddWithValue("@idanagrafica", verbale.idanagrafica);
                    cmd.Parameters.AddWithValue("@idviolazione", verbale.idviolazione);

                    cmd.ExecuteNonQuery();
                }

                _connection.Close();
                return RedirectToAction("Index");

            }
            return View(verbale);
        }
    }
}

progetto_settimanale/Controllers/ViolazioneController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using progetto_settimanale.Models;

namespace progetto_settimanale.Controllers
{
    public class ViolazioneController : Controller
    {
        private readonly SqlConnection _connection;

        public ViolazioneController(SqlConnection connection)
        {
            _connection = connection;
        }

        public IActionResult Index()
        {
            var violazioni = new List<Violazione>();
            _connection.Open();
            string query = "SELECT * FROM TIPO_VIOLAZIONE";
            using(SqlCommand cmd = new SqlCommand(query, _connection))
            {
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        violazioni.Add(new Violazione()
                        {
                            idviolazione = reader.GetInt32(0),
                            descrizione = reader.GetString(1),
                        });
                    }
                }
            }
            _connection.Close();
                return View(violazioni);
        }

        public IActionResult Aggiungi()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Aggiungi(Violazione violazione)
        {
            if (ModelState.IsValid)
            {
                _connection.Open();
                var query = "INSERT INTO TIPO_VIOLAZIONE (descrizione) VALUES (@descrizione)";
                using (var cmd = new SqlCommand(query, _connection)) {
                    cmd.Parameters.AddWithValue("@descrizione", violazione.descrizione);
                    cmd.ExecuteNonQuery();
                }
                _connection.Close();

                return RedirectToAction("Index");
            }

            return View(violazione);
        }
    }
}

progetto_settimanale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - progetto_settimanale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/progetto_settimanale.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Anagrafica" asp-action="Index">Epicode Municipale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false" role="button">
                                Anagrafica
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Anagrafica" asp-action="Index">Lista Anagrafica</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Anagrafica" asp-action="Aggiungi">Aggiungi Anagrafica</a></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false" role="button">
                                Violazioni
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Violazione" asp-action="Index">Lista Violazioni</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Violazione" asp-action="Aggiungi">Aggiungi Violazione</a></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" aria-expanded="false" role="button">
                                Verbali
                            </a>
                            <ul class="dropdown-menu dropdown-menu-light">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Verbale" asp-action="Index">Lista Verbali</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Verbale" asp-action="Aggiungi">Aggiungi Verbale</a></li>

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>


                    
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Epicode Municipale
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>